runtime: python37
instance_class: F4
entrypoint: uwsgi --http-socket :$PORT --wsgi-file main.py --callable app --master --processes 4
handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
